service: custom-serverless-url-shortener

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    PROJECT_NAME: serverless-url-shortener
    URL_TABLE: ${self:provider.environment.PROJECT_NAME}-url-table-${self:provider.stage}
    CONFIG_TABLE: ${self:provider.environment.PROJECT_NAME}-config-table-${self:provider.stage}

functions:
  urlRedirect:
    handler: src/lambda/http/urlRedirect.handler
    events:
      - http:
          method: get
          path: /{urlId}

resources:
  Resources:
    UrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: urlId
            AttributeType: S
        KeySchema:
          - AttributeName: urlId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.URL_TABLE}
    ConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: configKey
            AttributeType: S
        KeySchema:
          - AttributeName: configKey
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.CONFIG_TABLE}