service: custom-serverless-url-shortener

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    PROJECT_NAME: serverless-url-shortener
    SHORT_URL_TABLE: ${self:provider.environment.PROJECT_NAME}-short-url-table-${self:provider.stage}
    CONFIG_TABLE: ${self:provider.environment.PROJECT_NAME}-config-table-${self:provider.stage}

functions:

  shortUrlRedirect:
    handler: src/lambda/http/shortUrlRedirect.handler
    events:
      - http:
          method: get
          path: /{urlId}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: !GetAtt UrlTable.Arn

  createShortUrl:
    handler: src/lambda/http/createShortUrl.handler
    events:
      - http:
          method: post
          path: shortUrls
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt UrlTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt ConfigTable.Arn

  updateShortUrl:
    handler: src/lambda/http/updateShortUrl.handler
    events:
      - http:
          method: patch
          path: shortUrls/{shortUrlId}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItm
        Resource: !GetAtt UrlTable.Arn

  deleteShortUrl:
    handler: src/lambda/http/deleteShortUrl.handler
    events:
      - http:
          method: delete
          path: shortUrls/{shortUrlId}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: !GetAtt UrlTable.Arn

resources:
  Resources:
    UrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: urlId
            AttributeType: S
        KeySchema:
          - AttributeName: urlId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.SHORT_URL_TABLE}
    ConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: configKey
            AttributeType: S
        KeySchema:
          - AttributeName: configKey
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.CONFIG_TABLE}