service: custom-serverless-url-shortener

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  hello:
    handler: src/lambda/http/urlRedirect.handler
    events:
      - http:
          method: get
          path: /{urlId}

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
